"""
knotify-chat-resolver Lambda handler — extended by story 8.4.

This is an AppSync Lambda resolver (not an HTTP API Gateway proxy event).
AppSync invokes this Lambda for every resolver field that is mapped to the
chat_resolver data source.  The event shape is:

    {
        "typeName":  "Query" | "Mutation" | "Subscription",
        "fieldName": "<field>",
        "identity":  {
            "sub": "<cognito-sub>",
            "issuer": "...",
            "claims": {
                "sub": "...",
                "custom:profile_complete": "true" | "false",
                ...
            }
        },
        "arguments": { ... },
        "source": null | {...},
        ...
    }

Story 8.0 ships an EMPTY dispatcher that returns a structured
{"errorType": "Unimplemented", "message": "..."} for every (typeName, fieldName)
pair.  Story 8.3 wires (Mutation, createOrGetRoom) to _handle_create_or_get_room.
Story 8.4 wires (Mutation, sendMessage) to _handle_send_message.
Later stories (8.5, 8.7, 8.8) slot further concrete implementations
into _dispatch() without touching this scaffold.

Design decisions recorded here so later stories don't re-debate them:
  - knotify_db.block_filter() is the ONLY acceptable block-exclusion mechanism.
    Hand-rolled NOT EXISTS subqueries are forbidden (hotfix #87 lesson).
  - The @require_profile_complete_appsync decorator reads
    event["identity"]["claims"]["custom:profile_complete"] and returns
    Unauthorized when not "true".  It is applied at the handler entrypoint so
    every mutation and query is protected; subscription connect-path resolvers
    in the pipeline (story 8.6) add an explicit membership check instead.
  - Friendship check: inline SQL on the `friendships` table which stores
    canonical pairs (user_a < user_b) per migration 0004. No separate
    knotify_db.is_friend() helper exists; the query is a private helper here.
  - Block check: knotify_obs.is_blocked(conn, user_a, user_b) — bidirectional,
    single SELECT.  Used here; block_filter() is for row-set exclusion in
    list queries (not needed in createOrGetRoom).
  - sendMessage (story 8.4):
    - sender_id is ALWAYS sourced from identity.sub, never from GraphQL arguments.
    - No Notifications row is written for chat messages (§5.4.2 explicit rule).
    - ClientRequestToken = sha256(sender_id + "|" + room_id + "|" + content + "|"
      + str(floor(epoch_seconds))). Retries within the same wall-clock second
      produce the identical token; DynamoDB's 10-minute idempotency window
      deduplicates duplicate puts at the service layer.
    - SK of ChatMessages = "<iso-timestamp>#<ulid>".  ULID is generated by a
      minimal hand-rolled implementation that avoids adding a new pip dependency.

Dependencies (Lambda layers):
  - knotify_obs: init_logger, require_profile_complete_appsync, is_blocked,
                 chat_room_id
  - knotify_db:  get_connection
"""

from __future__ import annotations

import hashlib
import math
import os
import random
import time
from datetime import datetime, timezone
from typing import Any, Tuple

import knotify_db
from knotify_obs import chat_room_id, init_logger, is_blocked, require_profile_complete_appsync

# ---------------------------------------------------------------------------
# Module-level singletons (cold-start optimization)
# ---------------------------------------------------------------------------

logger = init_logger("knotify_chat_resolver")

_DB_SECRET_NAME: str = os.environ.get("DB_SECRET_NAME", "")

# Module-level DynamoDB client (reused across warm invocations).
# Lazy-initialised in _get_dynamodb(); avoids the import cost on cold start
# until the first real request arrives.
_dynamodb_client = None

# Module-level Aurora connection (reused across warm invocations).
# Lazy-initialised in _get_conn().
_conn = None

# ---------------------------------------------------------------------------
# Reason codes for Unauthorized responses.
#
# Defined as module-level string constants so downstream stories (8.4, 8.5,
# 8.7, 8.8) can import and reuse them without re-typing the literal strings.
# ---------------------------------------------------------------------------

REASON_NOT_FRIENDS: str = "NOT_FRIENDS"
REASON_BLOCKED: str = "BLOCKED"
REASON_SELF_CHAT: str = "SELF_CHAT"
REASON_ROOM_DEACTIVATED: str = "ROOM_DEACTIVATED"
REASON_ROOM_READ_ONLY: str = "ROOM_READ_ONLY"
# PROFILE_INCOMPLETE is returned by the @require_profile_complete_appsync
# decorator before this module's logic runs — no constant needed here, but
# documented for completeness.


def _get_dynamodb():
    """Return a (possibly cached) boto3 DynamoDB client."""
    global _dynamodb_client
    if _dynamodb_client is None:
        import boto3

        _dynamodb_client = boto3.client("dynamodb")
    return _dynamodb_client


def _get_conn():
    """Return a (possibly cached) Aurora psycopg2 connection."""
    global _conn
    if _conn is None or _conn.closed:
        _conn = knotify_db.get_connection(_DB_SECRET_NAME)
    return _conn


# ---------------------------------------------------------------------------
# Idempotency token — pure function, testable in isolation
# ---------------------------------------------------------------------------


def derive_client_request_token(
    sender_id: str,
    room_id: str,
    content: str,
    epoch_second: int,
) -> str:
    """Compute the deterministic ClientRequestToken for a sendMessage TransactWriteItems call.

    The token is a SHA-256 hex digest of the pipe-separated concatenation of
    (sender_id, room_id, content, epoch_second).  Retries that arrive within
    the same wall-clock second produce an identical token, so DynamoDB's
    10-minute idempotency window deduplicates duplicate TransactWriteItems calls
    at the service layer without any client-visible idempotency argument.

    Why SHA-256?  It is deterministic, collision-resistant, and available in
    Python's standard library — no extra dependency required.

    Args:
        sender_id:    Cognito sub of the message sender (server-set from JWT).
        room_id:      ChatRooms PK for the target room.
        content:      Message body as submitted by the caller.
        epoch_second: Floor of the current UTC epoch (seconds).  Injected by
                      the caller (not read here) so unit tests can exercise
                      determinism without depending on the system clock.

    Returns:
        64-character lowercase hex SHA-256 digest.
    """
    raw = f"{sender_id}|{room_id}|{content}|{epoch_second}"
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Minimal ULID generator (no new pip dependency)
#
# A ULID is a 26-character Crockford Base32 string encoding 128 bits:
#   - 48 bits: millisecond-precision Unix timestamp
#   - 80 bits: cryptographic randomness
#
# This implementation is intentionally minimal — just enough for the SK
# requirement SK = "<iso-timestamp>#<ulid>" in ChatMessages.  Full ULID
# spec: https://github.com/ulid/spec
# ---------------------------------------------------------------------------

_CROCKFORD_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"


def _generate_ulid() -> str:
    """Generate a new ULID string (26 uppercase Crockford Base32 characters).

    The ULID encodes the current millisecond timestamp in the first 10 chars
    and 80 bits of cryptographic randomness in the remaining 16 chars.

    Returns:
        26-character ULID string (e.g. '01ARZ3NDEKTSV4RRFFQ69G5FAV').
    """
    # Timestamp component: 48-bit millisecond epoch → 10 base-32 chars
    ts_ms = int(time.time() * 1000)
    ts_chars: list[str] = []
    remaining = ts_ms
    for _ in range(10):
        ts_chars.append(_CROCKFORD_ALPHABET[remaining & 0x1F])
        remaining >>= 5
    ts_chars.reverse()

    # Randomness component: 80 bits → 16 base-32 chars
    rand_bits = random.getrandbits(80)
    rand_chars: list[str] = []
    for _ in range(16):
        rand_chars.append(_CROCKFORD_ALPHABET[rand_bits & 0x1F])
        rand_bits >>= 5
    rand_chars.reverse()

    return "".join(ts_chars) + "".join(rand_chars)


# ---------------------------------------------------------------------------
# Shared response builders
# ---------------------------------------------------------------------------


def _unauthorized_response(reason: str) -> dict:
    """Return a structured AppSync Unauthorized error dict.

    Args:
        reason: One of the REASON_* constants above.

    Returns:
        {"errorType": "Unauthorized", "reason": <reason>}
    """
    return {"errorType": "Unauthorized", "reason": reason}


# ---------------------------------------------------------------------------
# Pure helpers
# ---------------------------------------------------------------------------


def _canonical_pair(user_a: str, user_b: str) -> Tuple[str, str]:
    """Return the two user IDs in lexicographic order (lo, hi).

    Mirrors the friendships table CHECK (user_a < user_b) constraint from
    migration 0004, so the pair can be used directly in a SQL WHERE clause.

    Args:
        user_a: UUID string of the first user.
        user_b: UUID string of the second user.

    Returns:
        Tuple (lo, hi) where lo <= hi lexicographically.
    """
    lo = min(user_a, user_b)
    hi = max(user_a, user_b)
    return lo, hi


# ---------------------------------------------------------------------------
# Friendship helper
#
# Friendship check: inline SQL rather than a separate knotify_db helper
# because no is_friend() function exists in knotify_db v1.  The friendships
# table stores canonical pairs (user_a < user_b per migration 0004 CHECK
# constraint), so a single SELECT on the canonical pair covers both directions.
# ---------------------------------------------------------------------------


def _is_friend(conn: Any, user_a: str, user_b: str) -> bool:
    """Return True if a friendship row exists for the canonical pair.

    The friendships table (migration 0004) stores rows with user_a < user_b
    enforced by a CHECK constraint, so there is exactly one row per friendship
    and a single parameterised SELECT on the canonical pair is sufficient.

    Args:
        conn:   An active psycopg2 connection.
        user_a: UUID of first user.
        user_b: UUID of second user.

    Returns:
        True if the friendship exists; False otherwise.
    """
    lo, hi = _canonical_pair(user_a, user_b)
    sql = (
        "SELECT 1 FROM friendships "
        "WHERE user_a = %s AND user_b = %s "
        "LIMIT 1"
    )
    with conn.cursor() as cur:
        cur.execute(sql, (lo, hi))
        return cur.fetchone() is not None


# ---------------------------------------------------------------------------
# createOrGetRoom handler — §5.4.1 flow
# ---------------------------------------------------------------------------


def _handle_create_or_get_room(event: dict) -> dict:
    """
    Implement the §5.4.1 idempotent room-creation flow.

    Steps:
      1. Extract caller and otherUserId from the event; reject SELF_CHAT.
      2. Open Aurora connection; check block (knotify_obs.is_blocked) — reject BLOCKED.
      3. Check friendship (_is_friend) — reject NOT_FRIENDS.
      4. Compute room_id = knotify_obs.chat_room_id(caller, other).
      5. TransactWriteItems: PutItem(ChatRooms) + 2 x PutItem(ChatRoomMembership),
         all conditional on attribute_not_exists(room_id) for ChatRooms and
         attribute_not_exists(user_id) for each ChatRoomMembership row.
      6. On success: return the new room dict.
      7. On TransactionCanceledException whose first reason is ConditionalCheckFailed
         (room already exists): GetItem(ChatRooms, room_id) and return the existing row.

    Args:
        event: AppSync Lambda resolver event dict.

    Returns:
        ChatRoom dict on success, or an Unauthorized error dict on failure.
    """
    caller_id: str = event.get("identity", {}).get("sub", "")
    other_user_id: str = event.get("arguments", {}).get("otherUserId", "")

    # 1. Self-chat guard
    if caller_id == other_user_id:
        return _unauthorized_response(REASON_SELF_CHAT)

    conn = _get_conn()
    try:
        # 2. Block check (bidirectional)
        if is_blocked(conn, caller_id, other_user_id):
            return _unauthorized_response(REASON_BLOCKED)

        # 3. Friendship check
        if not _is_friend(conn, caller_id, other_user_id):
            return _unauthorized_response(REASON_NOT_FRIENDS)
    finally:
        # Release any implicit transaction; connection stays cached for reuse.
        try:
            conn.rollback()
        except Exception:
            pass

    # 4. Deterministic room ID
    room_id: str = chat_room_id(caller_id, other_user_id)
    lo, hi = _canonical_pair(caller_id, other_user_id)

    ddb = _get_dynamodb()

    # 5. Atomic write — ChatRooms row + 2 ChatRoomMembership rows.
    #    All three Put items are conditional so the operation is idempotent:
    #    - ChatRooms: attribute_not_exists(room_id)
    #    - ChatRoomMembership: attribute_not_exists(user_id)  (per-row SK is room_id)
    transact_items = [
        {
            "Put": {
                "TableName": "ChatRooms",
                "Item": {
                    "room_id": {"S": room_id},
                    "user_a": {"S": lo},
                    "user_b": {"S": hi},
                    "status": {"S": "active"},
                    "friendship_active": {"BOOL": True},
                },
                "ConditionExpression": "attribute_not_exists(room_id)",
            }
        },
        {
            "Put": {
                "TableName": "ChatRoomMembership",
                "Item": {
                    "user_id": {"S": caller_id},
                    "room_id": {"S": room_id},
                },
                # attribute_not_exists(room_id) checks the SK — this (user_id, room_id)
                # composite key is unique per membership row. Using attribute_not_exists
                # on the SK correctly scopes the guard to "this user is not already in
                # this specific room" rather than "this user has no membership at all".
                "ConditionExpression": "attribute_not_exists(room_id)",
            }
        },
        {
            "Put": {
                "TableName": "ChatRoomMembership",
                "Item": {
                    "user_id": {"S": other_user_id},
                    "room_id": {"S": room_id},
                },
                "ConditionExpression": "attribute_not_exists(room_id)",
            }
        },
    ]

    try:
        ddb.transact_write_items(TransactItems=transact_items)
        logger.info(
            "create_or_get_room_created",
            extra={"room_id": room_id, "caller_id": caller_id},
        )
        return {
            "room_id": room_id,
            "user_a": lo,
            "user_b": hi,
            "status": "active",
            "friendship_active": True,
        }
    except Exception as exc:
        # 7. Detect ConditionalCheckFailed — room already exists.
        #    DynamoDB raises TransactionCanceledException with a CancellationReasons
        #    list; at least one entry has Code == "ConditionalCheckFailed".
        if _is_conditional_check_failed(exc):
            logger.info(
                "create_or_get_room_exists",
                extra={"room_id": room_id, "caller_id": caller_id},
            )
            return _fetch_existing_room(ddb, room_id)
        # Any other DynamoDB error propagates — Lambda will return a 500 to AppSync.
        raise


def _is_conditional_check_failed(exc: Exception) -> bool:
    """Return True when exc is a DynamoDB TransactionCanceledException with
    at least one ConditionalCheckFailed cancellation reason.

    Works with both botocore.exceptions.ClientError (production) and
    plain Exception subclasses with a matching response attribute (unit tests).
    """
    response = getattr(exc, "response", None)
    if response is None:
        return False
    error_code = response.get("Error", {}).get("Code", "")
    if error_code != "TransactionCanceledException":
        return False
    reasons = response.get("CancellationReasons", [])
    return any(r.get("Code") == "ConditionalCheckFailed" for r in reasons)


def _fetch_existing_room(ddb: Any, room_id: str) -> dict:
    """GetItem the existing ChatRooms row and return it as a plain dict.

    Args:
        ddb:     Boto3 DynamoDB client.
        room_id: The room's hash key.

    Returns:
        ChatRoom dict decoded from the DynamoDB item.
    """
    response = ddb.get_item(
        TableName="ChatRooms",
        Key={"room_id": {"S": room_id}},
    )
    item = response.get("Item", {})
    return {
        "room_id": item.get("room_id", {}).get("S", room_id),
        "user_a": item.get("user_a", {}).get("S", ""),
        "user_b": item.get("user_b", {}).get("S", ""),
        "status": item.get("status", {}).get("S", ""),
        "friendship_active": item.get("friendship_active", {}).get("BOOL", False),
    }


# ---------------------------------------------------------------------------
# sendMessage handler — §5.4 / story 8.4
# ---------------------------------------------------------------------------


def _handle_send_message(event: dict) -> dict:
    """
    Implement the sendMessage mutation.

    Steps:
      1. Extract sender_id from identity.sub (NEVER from GraphQL arguments).
         Extract room_id and content from arguments.
      2. GetItem ChatRoomMembership(sender_id, room_id) — reject Unauthorized
         if the row is absent (sender is not a member).
      3. GetItem ChatRooms(room_id) — reject RoomDeactivated if status != 'active';
         reject RoomReadOnly if friendship_active != true.
      4. Compute SK = "<iso-timestamp>#<ulid>" (server-set delivered_at).
      5. Compute ClientRequestToken = derive_client_request_token(sender_id,
         room_id, content, floor(time.time())).  Retries within the same
         wall-clock second carry an identical token and are deduplicated by
         DynamoDB's 10-minute idempotency window.
      6. TransactWriteItems:
           - PutItem ChatMessages (room_id PK, SK, sender_id, content,
             content_type, delivered_at).
           - UpdateItem ChatRooms (last_message_id, last_message_at,
             last_message_preview, last_message_sender_id).
         No Notifications row is written — chat messages are NOT logged to the
         Notifications table (§5.4.2 explicit rule).

    Args:
        event: AppSync Lambda resolver event dict.

    Returns:
        Message dict on success, or an error dict on failure.
    """
    sender_id: str = event.get("identity", {}).get("sub", "")
    arguments: dict = event.get("arguments", {})
    room_id: str = arguments.get("roomId", "")
    content: str = arguments.get("content", "")
    content_type: str = arguments.get("contentType", "text")

    ddb = _get_dynamodb()

    # 2. Membership check — sender must be in the room.
    membership_resp = ddb.get_item(
        TableName="ChatRoomMembership",
        Key={
            "user_id": {"S": sender_id},
            "room_id": {"S": room_id},
        },
    )
    if "Item" not in membership_resp:
        return _unauthorized_response(REASON_NOT_FRIENDS)

    # 3. Room status + friendship_active check.
    room_resp = ddb.get_item(
        TableName="ChatRooms",
        Key={"room_id": {"S": room_id}},
    )
    room_item = room_resp.get("Item", {})
    room_status: str = room_item.get("status", {}).get("S", "")
    friendship_active: bool = room_item.get("friendship_active", {}).get("BOOL", False)

    if room_status != "active":
        return {
            "errorType": "RoomDeactivated",
            "message": "The chat room is deactivated.",
            "reason": REASON_ROOM_DEACTIVATED,
        }
    if not friendship_active:
        return {
            "errorType": "RoomReadOnly",
            "message": "The chat room is read-only (friendship inactive).",
            "reason": REASON_ROOM_READ_ONLY,
        }

    # 4. Build SK: "<iso-timestamp>#<ulid>".
    now = datetime.now(tz=timezone.utc)
    delivered_at: str = now.isoformat()
    ulid: str = _generate_ulid()
    message_sk: str = f"{delivered_at}#{ulid}"

    # 5. Deterministic idempotency token — epoch_second injected (not read
    #    inside derive_client_request_token) so the function stays pure.
    epoch_second: int = int(time.time())
    client_request_token: str = derive_client_request_token(
        sender_id=sender_id,
        room_id=room_id,
        content=content,
        epoch_second=epoch_second,
    )

    # Preview truncated to 80 chars for the room-list UI (§5.4 architecture).
    preview: str = content[:80]

    # 6. Atomic write: ChatMessages PutItem + ChatRooms UpdateItem.
    #    No Notifications row — §5.4.2 explicit rule.
    transact_items = [
        {
            "Put": {
                "TableName": "ChatMessages",
                "Item": {
                    "room_id": {"S": room_id},
                    "sk": {"S": message_sk},
                    "sender_id": {"S": sender_id},
                    "content": {"S": content},
                    "content_type": {"S": content_type},
                    "delivered_at": {"S": delivered_at},
                },
            }
        },
        {
            "Update": {
                "TableName": "ChatRooms",
                "Key": {"room_id": {"S": room_id}},
                "UpdateExpression": (
                    "SET last_message_id = :msg_id, "
                    "last_message_at = :msg_at, "
                    "last_message_preview = :preview, "
                    "last_message_sender_id = :sender"
                ),
                "ExpressionAttributeValues": {
                    ":msg_id": {"S": message_sk},
                    ":msg_at": {"S": delivered_at},
                    ":preview": {"S": preview},
                    ":sender": {"S": sender_id},
                },
            }
        },
    ]

    ddb.transact_write_items(
        TransactItems=transact_items,
        ClientRequestToken=client_request_token,
    )

    logger.info(
        "send_message_success",
        extra={
            "room_id": room_id,
            "sender_id": sender_id,
            "message_sk": message_sk,
        },
    )

    # Response fields match the GraphQL Message type in schema.graphql (story 8.2):
    #   roomId, createdAt, messageId, senderId, content, contentType, deliveredAt.
    # messageId = the full SK value (<iso>#<ulid>) which AppSync clients use as a
    # cursor and which the subscription field filter targets.
    # createdAt mirrors deliveredAt (server-set timestamp); both are the same moment.
    return {
        "roomId": room_id,
        "messageId": message_sk,
        "createdAt": delivered_at,
        "senderId": sender_id,
        "content": content,
        "contentType": content_type,
        "deliveredAt": delivered_at,
    }


# ---------------------------------------------------------------------------
# AppSync resolver dispatcher
#
# The single entry point for all (typeName, fieldName) pairs routed to this
# Lambda via the AppSync data source configuration.
#
# Return value conventions for AppSync Lambda resolvers:
#   Success  → any serialisable dict / list (AppSync merges it into the
#               GraphQL response data).
#   Error    → {"errorType": "<ErrorCode>", "message": "<human-readable>",
#               "reason": "<machine-code>"}  — AppSync surfaces these as
#               GraphQL errors with extensions.errorType and extensions.reason.
# ---------------------------------------------------------------------------


def _dispatch(event: dict) -> Any:
    """
    Route the AppSync resolver event to the appropriate sub-handler.

    Wired so far:
        (Mutation, createOrGetRoom) → _handle_create_or_get_room  [story 8.3]
        (Mutation, sendMessage)     → _handle_send_message         [story 8.4]

    Later stories add:
        (Query,    listMyRooms)     → _handle_list_my_rooms        [story 8.5]
        ...

    Args:
        event: AppSync Lambda resolver event dict.

    Returns:
        A dict that AppSync merges into the GraphQL response.
    """
    type_name: str = event.get("typeName", "")
    field_name: str = event.get("fieldName", "")

    logger.info(
        "chat_resolver_dispatch",
        extra={"type_name": type_name, "field_name": field_name},
    )

    if type_name == "Mutation" and field_name == "createOrGetRoom":
        return _handle_create_or_get_room(event)

    if type_name == "Mutation" and field_name == "sendMessage":
        return _handle_send_message(event)

    return {
        "errorType": "Unimplemented",
        "message": f"{type_name}.{field_name} not yet implemented",
    }


# ---------------------------------------------------------------------------
# Lambda entrypoint
# ---------------------------------------------------------------------------


@require_profile_complete_appsync
def handler(event: dict, context: object) -> Any:
    """
    knotify-chat-resolver Lambda entrypoint.

    Validates the caller's profile-completion claim (via
    @require_profile_complete_appsync) and dispatches to the appropriate
    sub-handler based on (typeName, fieldName).

    Args:
        event:   AppSync Lambda resolver event dict.
        context: Lambda context object (unused).

    Returns:
        AppSync resolver response — a serialisable dict or list on success,
        or an error dict with errorType/message on failure.
    """
    user_id: str = (
        event.get("identity", {}).get("sub", "<unknown>")
    )

    logger.info(
        "chat_resolver_invoked",
        extra={
            "user_id": user_id,
            "type_name": event.get("typeName"),
            "field_name": event.get("fieldName"),
        },
    )

    return _dispatch(event)
