"""
knotify-chat-resolver Lambda handler — extended by story 8.4.

This is an AppSync Lambda resolver (not an HTTP API Gateway proxy event).
AppSync invokes this Lambda for every resolver field that is mapped to the
chat_resolver data source.  The event shape is:

    {
        "typeName":  "Query" | "Mutation" | "Subscription",
        "fieldName": "<field>",
        "identity":  {
            "sub": "<cognito-sub>",
            "issuer": "...",
            "claims": {
                "sub": "...",
                "custom:profile_complete": "true" | "false",
                ...
            }
        },
        "arguments": { ... },
        "source": null | {...},
        ...
    }

Story 8.0 ships an EMPTY dispatcher that returns a structured
{"errorType": "Unimplemented", "message": "..."} for every (typeName, fieldName)
pair.  Story 8.3 wires (Mutation, createOrGetRoom) to _handle_create_or_get_room.
Story 8.4 wires (Mutation, sendMessage) to _handle_send_message.
Story 8.5 wires (Query, listMyRooms) and (Query, messagesByChatRoom).
Later stories (8.7, 8.8) slot further concrete implementations
into _dispatch() without touching this scaffold.

Design decisions recorded here so later stories don't re-debate them:
  - knotify_db.block_filter() is the ONLY acceptable block-exclusion mechanism.
    Hand-rolled NOT EXISTS subqueries are forbidden (hotfix #87 lesson).
  - The @require_profile_complete_appsync decorator reads
    event["identity"]["claims"]["custom:profile_complete"] and returns
    Unauthorized when not "true".  It is applied at the handler entrypoint so
    every mutation and query is protected; subscription connect-path resolvers
    in the pipeline (story 8.6) add an explicit membership check instead.
  - Friendship check: inline SQL on the `friendships` table which stores
    canonical pairs (user_a < user_b) per migration 0004. No separate
    knotify_db.is_friend() helper exists; the query is a private helper here.
  - Block check: knotify_obs.is_blocked(conn, user_a, user_b) — bidirectional,
    single SELECT.  Used here; block_filter() is for row-set exclusion in
    list queries (not needed in createOrGetRoom).
  - sendMessage (story 8.4):
    - sender_id is ALWAYS sourced from identity.sub, never from GraphQL arguments.
    - No Notifications row is written for chat messages (§5.4.2 explicit rule).
    - ClientRequestToken = sha256(sender_id + "|" + room_id + "|" + content + "|"
      + str(floor(epoch_seconds))). Retries within the same wall-clock second
      produce the identical token; DynamoDB's 10-minute idempotency window
      deduplicates duplicate puts at the service layer.
    - SK of ChatMessages = "<iso-timestamp>#<ulid>".  ULID is generated by a
      minimal hand-rolled implementation that avoids adding a new pip dependency.
  - listMyRooms / messagesByChatRoom (story 8.5):
    - BatchGetItem on ChatRooms accepts up to 100 keys per call.
      TODO(phase-11-hardening): implement paginated BatchGetItem for users with
      > 100 rooms. For v1 nobody will exceed this cap.
    - nextToken is the base64-encoded JSON of DynamoDB's LastEvaluatedKey.
      Helpers: _encode_next_token / _decode_next_token (pure functions).
    - messagesByChatRoom default limit = 20; defensive cap = 100. Client-supplied
      limit values above 100 are silently clamped. This is intentional: it
      prevents a malicious or buggy client from causing excessive DynamoDB reads.

Dependencies (Lambda layers):
  - knotify_obs: init_logger, require_profile_complete_appsync, is_blocked,
                 chat_room_id
  - knotify_db:  get_connection
"""

from __future__ import annotations

import base64
import hashlib
import json
import math
import os
import random
import time
from datetime import datetime, timezone
from typing import Any, Tuple

import knotify_db
from knotify_obs import chat_room_id, init_logger, is_blocked, require_profile_complete_appsync

# ---------------------------------------------------------------------------
# Module-level singletons (cold-start optimization)
# ---------------------------------------------------------------------------

logger = init_logger("knotify_chat_resolver")

_DB_SECRET_NAME: str = os.environ.get("DB_SECRET_NAME", "")

# Module-level DynamoDB client (reused across warm invocations).
# Lazy-initialised in _get_dynamodb(); avoids the import cost on cold start
# until the first real request arrives.
_dynamodb_client = None

# Module-level Aurora connection (reused across warm invocations).
# Lazy-initialised in _get_conn().
_conn = None

# ---------------------------------------------------------------------------
# Reason codes for Unauthorized responses.
#
# Defined as module-level string constants so downstream stories (8.4, 8.5,
# 8.7, 8.8) can import and reuse them without re-typing the literal strings.
# ---------------------------------------------------------------------------

REASON_NOT_FRIENDS: str = "NOT_FRIENDS"
REASON_BLOCKED: str = "BLOCKED"
REASON_SELF_CHAT: str = "SELF_CHAT"
REASON_ROOM_DEACTIVATED: str = "ROOM_DEACTIVATED"
REASON_ROOM_READ_ONLY: str = "ROOM_READ_ONLY"
# PROFILE_INCOMPLETE is returned by the @require_profile_complete_appsync
# decorator before this module's logic runs — no constant needed here, but
# documented for completeness.

# Default and cap for messagesByChatRoom pagination (story 8.5).
_MESSAGES_DEFAULT_LIMIT: int = 20
# Defensive cap: silently clamp client-supplied limit to 100.
# Prevents a malicious or buggy client from issuing huge DynamoDB reads.
# TODO(phase-11-hardening): expose a configurable max via env var if needed.
_MESSAGES_MAX_LIMIT: int = 100


# ---------------------------------------------------------------------------
# Pagination helpers — story 8.5
#
# nextToken is the base64-encoded JSON of DynamoDB's LastEvaluatedKey.
# Both functions are pure (no I/O, no side effects) so they are trivially
# unit-testable without any AWS credentials or mocking.
# ---------------------------------------------------------------------------


def _encode_next_token(last_evaluated_key: dict | None) -> str | None:
    """Encode a DynamoDB LastEvaluatedKey into an opaque base64 nextToken string.

    Args:
        last_evaluated_key: The LastEvaluatedKey dict returned by a DynamoDB Query,
            or None when there are no more pages.

    Returns:
        Base64-encoded JSON string when last_evaluated_key is not None, else None.
    """
    if last_evaluated_key is None:
        return None
    raw_json = json.dumps(last_evaluated_key, separators=(",", ":"))
    return base64.b64encode(raw_json.encode("utf-8")).decode("ascii")


def _decode_next_token(token: str | None) -> dict | None:
    """Decode an opaque nextToken string back into a DynamoDB ExclusiveStartKey.

    Args:
        token: A base64 nextToken string from a previous MessageConnection
            response, or None to start from the beginning.

    Returns:
        Dict suitable for use as DynamoDB ExclusiveStartKey, or None when
        token is None (no cursor — start from the beginning).
    """
    if token is None:
        return None
    raw_json = base64.b64decode(token.encode("ascii")).decode("utf-8")
    return json.loads(raw_json)


def _get_dynamodb():
    """Return a (possibly cached) boto3 DynamoDB client."""
    global _dynamodb_client
    if _dynamodb_client is None:
        import boto3

        _dynamodb_client = boto3.client("dynamodb")
    return _dynamodb_client


def _get_conn():
    """Return a (possibly cached) Aurora psycopg2 connection."""
    global _conn
    if _conn is None or _conn.closed:
        _conn = knotify_db.get_connection(_DB_SECRET_NAME)
    return _conn


# ---------------------------------------------------------------------------
# Idempotency token — pure function, testable in isolation
# ---------------------------------------------------------------------------


def derive_client_request_token(
    sender_id: str,
    room_id: str,
    content: str,
    epoch_second: int,
) -> str:
    """Compute the deterministic ClientRequestToken for a sendMessage TransactWriteItems call.

    The token is a SHA-256 hex digest of the pipe-separated concatenation of
    (sender_id, room_id, content, epoch_second).  Retries that arrive within
    the same wall-clock second produce an identical token, so DynamoDB's
    10-minute idempotency window deduplicates duplicate TransactWriteItems calls
    at the service layer without any client-visible idempotency argument.

    Why SHA-256?  It is deterministic, collision-resistant, and available in
    Python's standard library — no extra dependency required.

    Args:
        sender_id:    Cognito sub of the message sender (server-set from JWT).
        room_id:      ChatRooms PK for the target room.
        content:      Message body as submitted by the caller.
        epoch_second: Floor of the current UTC epoch (seconds).  Injected by
                      the caller (not read here) so unit tests can exercise
                      determinism without depending on the system clock.

    Returns:
        64-character lowercase hex SHA-256 digest.
    """
    raw = f"{sender_id}|{room_id}|{content}|{epoch_second}"
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Minimal ULID generator (no new pip dependency)
#
# A ULID is a 26-character Crockford Base32 string encoding 128 bits:
#   - 48 bits: millisecond-precision Unix timestamp
#   - 80 bits: cryptographic randomness
#
# This implementation is intentionally minimal — just enough for the SK
# requirement SK = "<iso-timestamp>#<ulid>" in ChatMessages.  Full ULID
# spec: https://github.com/ulid/spec
# ---------------------------------------------------------------------------

_CROCKFORD_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"


def _generate_ulid() -> str:
    """Generate a new ULID string (26 uppercase Crockford Base32 characters).

    The ULID encodes the current millisecond timestamp in the first 10 chars
    and 80 bits of cryptographic randomness in the remaining 16 chars.

    Returns:
        26-character ULID string (e.g. '01ARZ3NDEKTSV4RRFFQ69G5FAV').
    """
    # Timestamp component: 48-bit millisecond epoch → 10 base-32 chars
    ts_ms = int(time.time() * 1000)
    ts_chars: list[str] = []
    remaining = ts_ms
    for _ in range(10):
        ts_chars.append(_CROCKFORD_ALPHABET[remaining & 0x1F])
        remaining >>= 5
    ts_chars.reverse()

    # Randomness component: 80 bits → 16 base-32 chars
    rand_bits = random.getrandbits(80)
    rand_chars: list[str] = []
    for _ in range(16):
        rand_chars.append(_CROCKFORD_ALPHABET[rand_bits & 0x1F])
        rand_bits >>= 5
    rand_chars.reverse()

    return "".join(ts_chars) + "".join(rand_chars)


# ---------------------------------------------------------------------------
# Shared response builders
# ---------------------------------------------------------------------------


def _unauthorized_response(reason: str) -> dict:
    """Return a structured AppSync Unauthorized error dict.

    Args:
        reason: One of the REASON_* constants above.

    Returns:
        {"errorType": "Unauthorized", "reason": <reason>}
    """
    return {"errorType": "Unauthorized", "reason": reason}


# ---------------------------------------------------------------------------
# Pure helpers
# ---------------------------------------------------------------------------


def _canonical_pair(user_a: str, user_b: str) -> Tuple[str, str]:
    """Return the two user IDs in lexicographic order (lo, hi).

    Mirrors the friendships table CHECK (user_a < user_b) constraint from
    migration 0004, so the pair can be used directly in a SQL WHERE clause.

    Args:
        user_a: UUID string of the first user.
        user_b: UUID string of the second user.

    Returns:
        Tuple (lo, hi) where lo <= hi lexicographically.
    """
    lo = min(user_a, user_b)
    hi = max(user_a, user_b)
    return lo, hi


# ---------------------------------------------------------------------------
# Friendship helper
#
# Friendship check: inline SQL rather than a separate knotify_db helper
# because no is_friend() function exists in knotify_db v1.  The friendships
# table stores canonical pairs (user_a < user_b per migration 0004 CHECK
# constraint), so a single SELECT on the canonical pair covers both directions.
# ---------------------------------------------------------------------------


def _is_friend(conn: Any, user_a: str, user_b: str) -> bool:
    """Return True if a friendship row exists for the canonical pair.

    The friendships table (migration 0004) stores rows with user_a < user_b
    enforced by a CHECK constraint, so there is exactly one row per friendship
    and a single parameterised SELECT on the canonical pair is sufficient.

    Args:
        conn:   An active psycopg2 connection.
        user_a: UUID of first user.
        user_b: UUID of second user.

    Returns:
        True if the friendship exists; False otherwise.
    """
    lo, hi = _canonical_pair(user_a, user_b)
    sql = (
        "SELECT 1 FROM friendships "
        "WHERE user_a = %s AND user_b = %s "
        "LIMIT 1"
    )
    with conn.cursor() as cur:
        cur.execute(sql, (lo, hi))
        return cur.fetchone() is not None


# ---------------------------------------------------------------------------
# createOrGetRoom handler — §5.4.1 flow
# ---------------------------------------------------------------------------


def _handle_create_or_get_room(event: dict) -> dict:
    """
    Implement the §5.4.1 idempotent room-creation flow.

    Steps:
      1. Extract caller and otherUserId from the event; reject SELF_CHAT.
      2. Open Aurora connection; check block (knotify_obs.is_blocked) — reject BLOCKED.
      3. Check friendship (_is_friend) — reject NOT_FRIENDS.
      4. Compute room_id = knotify_obs.chat_room_id(caller, other).
      5. TransactWriteItems: PutItem(ChatRooms) + 2 x PutItem(ChatRoomMembership),
         all conditional on attribute_not_exists(room_id) for ChatRooms and
         attribute_not_exists(user_id) for each ChatRoomMembership row.
      6. On success: return the new room dict.
      7. On TransactionCanceledException whose first reason is ConditionalCheckFailed
         (room already exists): GetItem(ChatRooms, room_id) and return the existing row.

    Args:
        event: AppSync Lambda resolver event dict.

    Returns:
        ChatRoom dict on success, or an Unauthorized error dict on failure.
    """
    caller_id: str = event.get("identity", {}).get("sub", "")
    other_user_id: str = event.get("arguments", {}).get("otherUserId", "")

    # 1. Self-chat guard
    if caller_id == other_user_id:
        return _unauthorized_response(REASON_SELF_CHAT)

    conn = _get_conn()
    try:
        # 2. Block check (bidirectional)
        if is_blocked(conn, caller_id, other_user_id):
            return _unauthorized_response(REASON_BLOCKED)

        # 3. Friendship check
        if not _is_friend(conn, caller_id, other_user_id):
            return _unauthorized_response(REASON_NOT_FRIENDS)
    finally:
        # Release any implicit transaction; connection stays cached for reuse.
        try:
            conn.rollback()
        except Exception:
            pass

    # 4. Deterministic room ID
    room_id: str = chat_room_id(caller_id, other_user_id)
    lo, hi = _canonical_pair(caller_id, other_user_id)

    ddb = _get_dynamodb()

    # 5. Atomic write — ChatRooms row + 2 ChatRoomMembership rows.
    #    All three Put items are conditional so the operation is idempotent:
    #    - ChatRooms: attribute_not_exists(room_id)
    #    - ChatRoomMembership: attribute_not_exists(user_id)  (per-row SK is room_id)
    transact_items = [
        {
            "Put": {
                "TableName": "ChatRooms",
                "Item": {
                    "room_id": {"S": room_id},
                    "user_a": {"S": lo},
                    "user_b": {"S": hi},
                    "status": {"S": "active"},
                    "friendship_active": {"BOOL": True},
                },
                "ConditionExpression": "attribute_not_exists(room_id)",
            }
        },
        {
            "Put": {
                "TableName": "ChatRoomMembership",
                "Item": {
                    "user_id": {"S": caller_id},
                    "room_id": {"S": room_id},
                },
                # attribute_not_exists(room_id) checks the SK — this (user_id, room_id)
                # composite key is unique per membership row. Using attribute_not_exists
                # on the SK correctly scopes the guard to "this user is not already in
                # this specific room" rather than "this user has no membership at all".
                "ConditionExpression": "attribute_not_exists(room_id)",
            }
        },
        {
            "Put": {
                "TableName": "ChatRoomMembership",
                "Item": {
                    "user_id": {"S": other_user_id},
                    "room_id": {"S": room_id},
                },
                "ConditionExpression": "attribute_not_exists(room_id)",
            }
        },
    ]

    try:
        ddb.transact_write_items(TransactItems=transact_items)
        logger.info(
            "create_or_get_room_created",
            extra={"room_id": room_id, "caller_id": caller_id},
        )
        return {
            "room_id": room_id,
            "user_a": lo,
            "user_b": hi,
            "status": "active",
            "friendship_active": True,
        }
    except Exception as exc:
        # 7. Detect ConditionalCheckFailed — room already exists.
        #    DynamoDB raises TransactionCanceledException with a CancellationReasons
        #    list; at least one entry has Code == "ConditionalCheckFailed".
        if _is_conditional_check_failed(exc):
            logger.info(
                "create_or_get_room_exists",
                extra={"room_id": room_id, "caller_id": caller_id},
            )
            return _fetch_existing_room(ddb, room_id)
        # Any other DynamoDB error propagates — Lambda will return a 500 to AppSync.
        raise


def _is_conditional_check_failed(exc: Exception) -> bool:
    """Return True when exc is a DynamoDB TransactionCanceledException with
    at least one ConditionalCheckFailed cancellation reason.

    Works with both botocore.exceptions.ClientError (production) and
    plain Exception subclasses with a matching response attribute (unit tests).
    """
    response = getattr(exc, "response", None)
    if response is None:
        return False
    error_code = response.get("Error", {}).get("Code", "")
    if error_code != "TransactionCanceledException":
        return False
    reasons = response.get("CancellationReasons", [])
    return any(r.get("Code") == "ConditionalCheckFailed" for r in reasons)


def _fetch_existing_room(ddb: Any, room_id: str) -> dict:
    """GetItem the existing ChatRooms row and return it as a plain dict.

    Args:
        ddb:     Boto3 DynamoDB client.
        room_id: The room's hash key.

    Returns:
        ChatRoom dict decoded from the DynamoDB item.
    """
    response = ddb.get_item(
        TableName="ChatRooms",
        Key={"room_id": {"S": room_id}},
    )
    item = response.get("Item", {})
    return {
        "room_id": item.get("room_id", {}).get("S", room_id),
        "user_a": item.get("user_a", {}).get("S", ""),
        "user_b": item.get("user_b", {}).get("S", ""),
        "status": item.get("status", {}).get("S", ""),
        "friendship_active": item.get("friendship_active", {}).get("BOOL", False),
    }


# ---------------------------------------------------------------------------
# sendMessage handler — §5.4 / story 8.4
# ---------------------------------------------------------------------------


def _handle_send_message(event: dict) -> dict:
    """
    Implement the sendMessage mutation.

    Steps:
      1. Extract sender_id from identity.sub (NEVER from GraphQL arguments).
         Extract room_id and content from arguments.
      2. GetItem ChatRoomMembership(sender_id, room_id) — reject Unauthorized
         if the row is absent (sender is not a member).
      3. GetItem ChatRooms(room_id) — reject RoomDeactivated if status != 'active';
         reject RoomReadOnly if friendship_active != true.
      4. Compute SK = "<iso-timestamp>#<ulid>" (server-set delivered_at).
      5. Compute ClientRequestToken = derive_client_request_token(sender_id,
         room_id, content, floor(time.time())).  Retries within the same
         wall-clock second carry an identical token and are deduplicated by
         DynamoDB's 10-minute idempotency window.
      6. TransactWriteItems:
           - PutItem ChatMessages (room_id PK, SK, sender_id, content,
             content_type, delivered_at).
           - UpdateItem ChatRooms (last_message_id, last_message_at,
             last_message_preview, last_message_sender_id).
         No Notifications row is written — chat messages are NOT logged to the
         Notifications table (§5.4.2 explicit rule).

    Args:
        event: AppSync Lambda resolver event dict.

    Returns:
        Message dict on success, or an error dict on failure.
    """
    sender_id: str = event.get("identity", {}).get("sub", "")
    arguments: dict = event.get("arguments", {})
    room_id: str = arguments.get("roomId", "")
    content: str = arguments.get("content", "")
    content_type: str = arguments.get("contentType", "text")

    ddb = _get_dynamodb()

    # 2. Membership check — sender must be in the room.
    membership_resp = ddb.get_item(
        TableName="ChatRoomMembership",
        Key={
            "user_id": {"S": sender_id},
            "room_id": {"S": room_id},
        },
    )
    if "Item" not in membership_resp:
        return _unauthorized_response(REASON_NOT_FRIENDS)

    # 3. Room status + friendship_active check.
    room_resp = ddb.get_item(
        TableName="ChatRooms",
        Key={"room_id": {"S": room_id}},
    )
    room_item = room_resp.get("Item", {})
    room_status: str = room_item.get("status", {}).get("S", "")
    friendship_active: bool = room_item.get("friendship_active", {}).get("BOOL", False)

    if room_status != "active":
        return {
            "errorType": "RoomDeactivated",
            "message": "The chat room is deactivated.",
            "reason": REASON_ROOM_DEACTIVATED,
        }
    if not friendship_active:
        return {
            "errorType": "RoomReadOnly",
            "message": "The chat room is read-only (friendship inactive).",
            "reason": REASON_ROOM_READ_ONLY,
        }

    # 4. Build SK: "<iso-timestamp>#<ulid>".
    now = datetime.now(tz=timezone.utc)
    delivered_at: str = now.isoformat()
    ulid: str = _generate_ulid()
    message_sk: str = f"{delivered_at}#{ulid}"

    # 5. Deterministic idempotency token — epoch_second injected (not read
    #    inside derive_client_request_token) so the function stays pure.
    epoch_second: int = int(time.time())
    client_request_token: str = derive_client_request_token(
        sender_id=sender_id,
        room_id=room_id,
        content=content,
        epoch_second=epoch_second,
    )

    # Preview truncated to 80 chars for the room-list UI (§5.4 architecture).
    preview: str = content[:80]

    # 6. Atomic write: ChatMessages PutItem + ChatRooms UpdateItem.
    #    No Notifications row — §5.4.2 explicit rule.
    transact_items = [
        {
            "Put": {
                "TableName": "ChatMessages",
                "Item": {
                    "room_id": {"S": room_id},
                    "sk": {"S": message_sk},
                    "sender_id": {"S": sender_id},
                    "content": {"S": content},
                    "content_type": {"S": content_type},
                    "delivered_at": {"S": delivered_at},
                },
            }
        },
        {
            "Update": {
                "TableName": "ChatRooms",
                "Key": {"room_id": {"S": room_id}},
                "UpdateExpression": (
                    "SET last_message_id = :msg_id, "
                    "last_message_at = :msg_at, "
                    "last_message_preview = :preview, "
                    "last_message_sender_id = :sender"
                ),
                "ExpressionAttributeValues": {
                    ":msg_id": {"S": message_sk},
                    ":msg_at": {"S": delivered_at},
                    ":preview": {"S": preview},
                    ":sender": {"S": sender_id},
                },
            }
        },
    ]

    ddb.transact_write_items(
        TransactItems=transact_items,
        ClientRequestToken=client_request_token,
    )

    logger.info(
        "send_message_success",
        extra={
            "room_id": room_id,
            "sender_id": sender_id,
            "message_sk": message_sk,
        },
    )

    # Response fields match the GraphQL Message type in schema.graphql (story 8.2):
    #   roomId, createdAt, messageId, senderId, content, contentType, deliveredAt.
    # messageId = the full SK value (<iso>#<ulid>) which AppSync clients use as a
    # cursor and which the subscription field filter targets.
    # createdAt mirrors deliveredAt (server-set timestamp); both are the same moment.
    return {
        "roomId": room_id,
        "messageId": message_sk,
        "createdAt": delivered_at,
        "senderId": sender_id,
        "content": content,
        "contentType": content_type,
        "deliveredAt": delivered_at,
    }


# ---------------------------------------------------------------------------
# listMyRooms handler — story 8.5
# ---------------------------------------------------------------------------


def _decode_room(item: dict) -> dict:
    """Decode a DynamoDB ChatRooms item dict into a plain Python dict.

    Maps DynamoDB typed values ({S: ...}, {BOOL: ...}) to bare Python types
    and applies the camelCase field names from schema.graphql's ChatRoom type.

    Args:
        item: A single ChatRooms DynamoDB item returned by GetItem or BatchGetItem.

    Returns:
        ChatRoom dict with camelCase keys matching the GraphQL type.
    """
    return {
        "roomId": item.get("room_id", {}).get("S", ""),
        "userA": item.get("user_a", {}).get("S", ""),
        "userB": item.get("user_b", {}).get("S", ""),
        "status": item.get("status", {}).get("S", ""),
        "friendshipActive": item.get("friendship_active", {}).get("BOOL", False),
        "lastMessageId": item.get("last_message_id", {}).get("S"),
        "lastMessageAt": item.get("last_message_at", {}).get("S"),
        "lastMessagePreview": item.get("last_message_preview", {}).get("S"),
        "lastMessageSenderId": item.get("last_message_sender_id", {}).get("S"),
        "createdAt": item.get("created_at", {}).get("S"),
        "deactivatedReason": item.get("deactivated_reason", {}).get("S"),
        "deactivatedAt": item.get("deactivated_at", {}).get("S"),
        "deactivatedBy": item.get("deactivated_by", {}).get("S"),
        "reactivatedAt": item.get("reactivated_at", {}).get("S"),
    }


def _handle_list_my_rooms(event: dict) -> list:
    """
    Implement the listMyRooms Query.

    Steps:
      1. Query ChatRoomMembership (PK=identity.sub) to collect all room_id values
         the caller belongs to.
      2. BatchGetItem(ChatRooms, Keys=[...]) to fetch each room's full object.
         NOTE: BatchGetItem accepts up to 100 keys per call.
         TODO(phase-11-hardening): paginate BatchGetItem for users with > 100
         rooms. For v1 nobody will exceed this cap.
      3. Sort the resulting rooms by last_message_at descending (most-recent first).
         Rooms with no last_message_at (no messages yet) sort to the end.

    Args:
        event: AppSync Lambda resolver event dict.

    Returns:
        List of ChatRoom dicts, sorted by last_message_at descending.
    """
    caller_id: str = event.get("identity", {}).get("sub", "")
    ddb = _get_dynamodb()

    # 1. Query ChatRoomMembership: PK = caller_id
    membership_resp = ddb.query(
        TableName="ChatRoomMembership",
        KeyConditionExpression="user_id = :uid",
        ExpressionAttributeValues={":uid": {"S": caller_id}},
    )
    membership_items = membership_resp.get("Items", [])

    if not membership_items:
        return []

    room_ids: list[str] = [
        item["room_id"]["S"] for item in membership_items if "room_id" in item
    ]

    if not room_ids:
        return []

    # 2. BatchGetItem on ChatRooms.
    #    BatchGetItem accepts up to 100 Keys per call — for v1 we do not paginate.
    #    TODO(phase-11-hardening): chunk into batches of 100 when users can exceed
    #    this cap in a future release.
    keys = [{"room_id": {"S": rid}} for rid in room_ids]
    batch_resp = ddb.batch_get_item(
        RequestItems={"ChatRooms": {"Keys": keys}},
    )
    room_items = batch_resp.get("Responses", {}).get("ChatRooms", [])

    rooms = [_decode_room(item) for item in room_items]

    # 3. Sort by last_message_at descending.
    #    Rooms with no last_message_at (never received a message) sort to the end
    #    via the empty-string fallback (empty string < any ISO timestamp string).
    rooms.sort(key=lambda r: r.get("lastMessageAt") or "", reverse=True)

    logger.info(
        "list_my_rooms_success",
        extra={"caller_id": caller_id, "room_count": len(rooms)},
    )

    return rooms


# ---------------------------------------------------------------------------
# messagesByChatRoom handler — story 8.5
# ---------------------------------------------------------------------------


def _decode_message(item: dict) -> dict:
    """Decode a DynamoDB ChatMessages item into a plain dict matching Message type.

    The ChatMessages table SK is the "sk" attribute (written by sendMessage as
    "<iso-timestamp>#<ulid>").  The "createdAt" field mirrors the ISO timestamp
    prefix of the SK; "messageId" is the full SK value used as a cursor.

    Args:
        item: A single ChatMessages DynamoDB item.

    Returns:
        Message dict with camelCase keys matching the GraphQL Message type.
    """
    sk_value = item.get("sk", {}).get("S", "")
    # createdAt is the ISO timestamp prefix (before the '#' separator)
    created_at = sk_value.split("#")[0] if "#" in sk_value else sk_value
    return {
        "roomId": item.get("room_id", {}).get("S", ""),
        "messageId": sk_value,
        "createdAt": created_at,
        "senderId": item.get("sender_id", {}).get("S", ""),
        "content": item.get("content", {}).get("S", ""),
        "contentType": item.get("content_type", {}).get("S", "text"),
        "gifUrl": item.get("gif_url", {}).get("S"),
        "deliveredAt": item.get("delivered_at", {}).get("S", ""),
    }


def _handle_messages_by_chat_room(event: dict) -> dict:
    """
    Implement the messagesByChatRoom Query.

    Steps:
      1. GetItem(ChatRoomMembership, (identity.sub, roomId)) — reject Unauthorized
         if the caller is not a member of the room.
      2. Query(ChatMessages, PK=roomId, ScanIndexForward=False) — descending by SK
         (newest first). Apply SK condition > createdAtGt when supplied.
         Apply limit (default _MESSAGES_DEFAULT_LIMIT, cap _MESSAGES_MAX_LIMIT).
         Resume from nextToken (ExclusiveStartKey) when supplied.
      3. Encode DynamoDB LastEvaluatedKey into a nextToken for the response.

    Args:
        event: AppSync Lambda resolver event dict.

    Returns:
        MessageConnection dict: {"items": [Message, ...], "nextToken": str | None}
    """
    caller_id: str = event.get("identity", {}).get("sub", "")
    arguments: dict = event.get("arguments", {})
    room_id: str = arguments.get("roomId", "")
    created_at_gt: str | None = arguments.get("createdAtGt")
    client_limit: int | None = arguments.get("limit")
    next_token_in: str | None = arguments.get("nextToken")

    ddb = _get_dynamodb()

    # 1. Membership check: caller must be in the room.
    membership_resp = ddb.get_item(
        TableName="ChatRoomMembership",
        Key={
            "user_id": {"S": caller_id},
            "room_id": {"S": room_id},
        },
    )
    if "Item" not in membership_resp:
        return _unauthorized_response(REASON_NOT_FRIENDS)

    # 2. Compute effective limit.
    #    Default: _MESSAGES_DEFAULT_LIMIT (20).
    #    Defensive cap: _MESSAGES_MAX_LIMIT (100) — silently clamp any larger
    #    client-supplied value. This prevents excessive DynamoDB reads from a
    #    misconfigured or malicious client.
    effective_limit = _MESSAGES_DEFAULT_LIMIT
    if client_limit is not None:
        effective_limit = min(int(client_limit), _MESSAGES_MAX_LIMIT)

    # 3. Build DynamoDB Query parameters.
    query_kwargs: dict = {
        "TableName": "ChatMessages",
        "KeyConditionExpression": "room_id = :rid",
        "ExpressionAttributeValues": {":rid": {"S": room_id}},
        "ScanIndexForward": False,  # descending by SK (newest messages first)
        "Limit": effective_limit,
    }

    # Optional SK lower-bound filter: SK > createdAtGt
    # createdAtGt is an ISO timestamp prefix. Since the SK format is
    # "<iso-timestamp>#<ulid>", a begins_with or > comparison on the prefix
    # returns all messages created after the given timestamp.
    if created_at_gt:
        query_kwargs["KeyConditionExpression"] += (
            " AND sk > :cat_gt"
        )
        query_kwargs["ExpressionAttributeValues"][":cat_gt"] = {"S": created_at_gt}

    # Optional pagination cursor.
    exclusive_start_key = _decode_next_token(next_token_in)
    if exclusive_start_key is not None:
        query_kwargs["ExclusiveStartKey"] = exclusive_start_key

    messages_resp = ddb.query(**query_kwargs)
    raw_items = messages_resp.get("Items", [])
    last_evaluated_key = messages_resp.get("LastEvaluatedKey")

    messages = [_decode_message(item) for item in raw_items]
    next_token_out = _encode_next_token(last_evaluated_key)

    logger.info(
        "messages_by_chat_room_success",
        extra={
            "caller_id": caller_id,
            "room_id": room_id,
            "message_count": len(messages),
            "has_next_page": next_token_out is not None,
        },
    )

    # Return matches MessageConnection type in schema.graphql:
    #   { items: [Message!]!, nextToken: String }
    return {
        "items": messages,
        "nextToken": next_token_out,
    }


# ---------------------------------------------------------------------------
# AppSync resolver dispatcher
#
# The single entry point for all (typeName, fieldName) pairs routed to this
# Lambda via the AppSync data source configuration.
#
# Return value conventions for AppSync Lambda resolvers:
#   Success  → any serialisable dict / list (AppSync merges it into the
#               GraphQL response data).
#   Error    → {"errorType": "<ErrorCode>", "message": "<human-readable>",
#               "reason": "<machine-code>"}  — AppSync surfaces these as
#               GraphQL errors with extensions.errorType and extensions.reason.
# ---------------------------------------------------------------------------


def _dispatch(event: dict) -> Any:
    """
    Route the AppSync resolver event to the appropriate sub-handler.

    Wired so far:
        (Mutation, createOrGetRoom)      → _handle_create_or_get_room  [story 8.3]
        (Mutation, sendMessage)          → _handle_send_message         [story 8.4]
        (Query,    listMyRooms)          → _handle_list_my_rooms        [story 8.5]
        (Query,    messagesByChatRoom)   → _handle_messages_by_chat_room [story 8.5]

    Later stories add:
        ...

    Args:
        event: AppSync Lambda resolver event dict.

    Returns:
        A dict that AppSync merges into the GraphQL response.
    """
    type_name: str = event.get("typeName", "")
    field_name: str = event.get("fieldName", "")

    logger.info(
        "chat_resolver_dispatch",
        extra={"type_name": type_name, "field_name": field_name},
    )

    if type_name == "Mutation" and field_name == "createOrGetRoom":
        return _handle_create_or_get_room(event)

    if type_name == "Mutation" and field_name == "sendMessage":
        return _handle_send_message(event)

    if type_name == "Query" and field_name == "listMyRooms":
        return _handle_list_my_rooms(event)

    if type_name == "Query" and field_name == "messagesByChatRoom":
        return _handle_messages_by_chat_room(event)

    return {
        "errorType": "Unimplemented",
        "message": f"{type_name}.{field_name} not yet implemented",
    }


# ---------------------------------------------------------------------------
# Lambda entrypoint
# ---------------------------------------------------------------------------


@require_profile_complete_appsync
def handler(event: dict, context: object) -> Any:
    """
    knotify-chat-resolver Lambda entrypoint.

    Validates the caller's profile-completion claim (via
    @require_profile_complete_appsync) and dispatches to the appropriate
    sub-handler based on (typeName, fieldName).

    Args:
        event:   AppSync Lambda resolver event dict.
        context: Lambda context object (unused).

    Returns:
        AppSync resolver response — a serialisable dict or list on success,
        or an error dict with errorType/message on failure.
    """
    user_id: str = (
        event.get("identity", {}).get("sub", "<unknown>")
    )

    logger.info(
        "chat_resolver_invoked",
        extra={
            "user_id": user_id,
            "type_name": event.get("typeName"),
            "field_name": event.get("fieldName"),
        },
    )

    return _dispatch(event)
