-- Migration 0003: create siblings table
--
-- Creates the siblings table per architecture.md §5.1.
-- Stores sibling profile data as separate rows (1-to-many) linked to users
-- via a foreign key with ON DELETE CASCADE — deleting a user automatically
-- removes all associated sibling rows.
--
-- Columns match §5.1 exactly:
--   sibling_id     — UUID primary key, generated by gen_random_uuid() (pgcrypto)
--   user_id        — FK → users(user_id) ON DELETE CASCADE (NOT NULL)
--   name           — free-text sibling name
--   gender         — free-text gender (no CHECK, architecture imposes none)
--   sibling_age    — stored as TEXT per architecture (e.g. "28", "late 20s")
--   marital_status — free-text
--   profession     — free-text
--   created_at     — audit timestamp, default NOW()
--
-- Index:
--   idx_siblings_user — B-tree on user_id, supports "fetch all siblings for user"
--                       queries issued by Lambda profile endpoints

CREATE TABLE siblings (
    sibling_id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id          UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    name             TEXT,
    gender           TEXT,
    sibling_age      TEXT,
    marital_status   TEXT,
    profession       TEXT,
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_siblings_user ON siblings (user_id);
