-- Migration 0005: create friend_requests table
--
-- Creates the friend_requests table per architecture.md §5.1.
-- Tracks in-flight friend requests between users with a lifecycle status
-- ('pending' → 'accepted' | 'declined' | 'cancelled').
--
-- Columns per §5.1:
--   request_id   — UUID PK, generated by gen_random_uuid() (pgcrypto, enabled in 0001)
--   from_user_id — sender, FK → users(user_id) ON DELETE CASCADE
--   to_user_id   — recipient, FK → users(user_id) ON DELETE CASCADE
--   status       — TEXT with CHECK (status IN ('pending','accepted','declined','cancelled'))
--   created_at   — audit timestamp, default NOW()
--   responded_at — TIMESTAMPTZ, nullable, set when status changes from 'pending'
--
-- Constraints:
--   UNIQUE (from_user_id, to_user_id, status) — prevents duplicate pending requests;
--     a second 'pending' row between the same pair is rejected, but an 'accepted'
--     row can coexist (different status value, different unique tuple)
--
-- Indexes:
--   idx_fr_to_pending   — partial index on to_user_id WHERE status='pending';
--     supports "fetch all pending requests received by :user_id"
--   idx_fr_from_pending — partial index on from_user_id WHERE status='pending';
--     supports "fetch all pending requests sent by :user_id"

CREATE TABLE friend_requests (
    request_id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    from_user_id   UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    to_user_id     UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    status         TEXT NOT NULL CHECK (status IN ('pending', 'accepted', 'declined', 'cancelled')),
    created_at     TIMESTAMPTZ DEFAULT NOW(),
    responded_at   TIMESTAMPTZ,
    UNIQUE (from_user_id, to_user_id, status)
);

CREATE INDEX idx_fr_to_pending   ON friend_requests (to_user_id)   WHERE status = 'pending';
CREATE INDEX idx_fr_from_pending ON friend_requests (from_user_id) WHERE status = 'pending';
